

#Makefile for Project 1 - 4/7/17
#Assembled with the help of the following references: 
#http://mrbook.org/blog/tutorials/make/ (Course material found in Canvas) and "makefile1" TA example provided in Canvas

ClementeProject1: LangtonsAnt.cpp LangtonsAnt.hpp LangtonsAntMain.cpp Menu.cpp Menu.hpp UserInputValidation.cpp UserInputValidation.hpp
	g++ -g -std=c++0x LangtonsAntMain.cpp LangtonsAnt.cpp Menu.cpp UserInputValidation.cpp -o ClementeProject1
	
clean:
	rm *o